### ISSUE TITLE
Impossible access to items

### ISSUE THREAD

**Issue by ademasi** [Eonm/zotero#1]
Hi, 

Thank you for your work. I wanted to start playing with Zotero and Rust via your crate. 
But I am having some issues, I am using my own key generated on https://www.zotero.org/settings/keys  to access my items. Nothing get printed at all, looks like my username/password are not working.

Did I miss something ? (I am totally new to rust)

``` rust
    let z = ZoteroInit::set_user("XXXX", "YYYY");
    
    let items = z.get_items(None);

    for item in items {
        println!("{:#?}", item)
    }
    
```

Regards, Alex.

**Comment by Eonm** [comment]
Hi @ademasi ,

Thank you for your issue and welcome to the Rust community :crab:.

You should try something like this :

```rust
extern crate zotero;

use zotero::ZoteroInit;
use zotero::Get;

use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    let z = ZoteroInit::set_user("ID", "API_KEY");
    let items = z.get_items(None)?;
    
   for item in items.iter() {
     println!("{:?}", item);
   }

    Ok(())
}
```
The problem with your code is that `z.get_items(None)` returns a [Result](https://doc.rust-lang.org/stable/rust-by-example/error/result.html). A result holds a value or an Error. If you want to iter over a Result you need to get it's value first. To do so you can [unwrap](https://doc.rust-lang.org/stable/rust-by-example/error/option_unwrap.html) the Result whit : `z.get_items(None).unwrap()` or you can use [`?`](https://doc.rust-lang.org/edition-guide/rust-2018/error-handling-and-panics/the-question-mark-operator-for-easier-error-handling.html) operator as I did in my first example. Or You can also use pattern matching like this :

```rust
extern crate zotero;

use zotero::ZoteroInit;
use zotero::Get;

use std::error::Error;

fn main() {
    let z = ZoteroInit::set_user("ID", "API_KEY");
    let items = z.get_items(None);
    
    let items = z.get_items(None);
    
   match items {
     Ok(zotero_items) => println!("{:?}", zotero_items),
     Err(_) => panic!("API Error")
   }
}
```
If you want to check your API key privileges you should take a look at the [doc](https://docs.rs/zotero/0.0.2/zotero/trait.Get.html#method.get_api_key_info).

```rust
let z = ZoteroInit::set_user("ID", "API_KEY");
let key_info = z.get_api_key_info("API_KEY");
println!("{:?}", key_info);
```
While looking to fix your issue I noticed other issues with my crate. Zotero API slightly change since I implemented it and I'm facing Derialization issues :disappointed:. I need more time to fix this see #2.

Best regards

**Comment by ademasi** [comment]
Hi @Eonm , 

Thank you for taking the time to reply to my issue.

Indeed, I was expecting something closer to what I am used to in Python or Java. I need to read the rust book ...
Anyway, I was able to access my API key details with get_api_key_info. But as you saw, if I am trying to access an item, even directly with its ID, I get this this error :
```rust
Err(
    Error("invalid type: map, expected a string", line: 0, column: 0),
)
```
What would be the first step to hep with with #2 ?

Regards, Alex.

**Comment by Eonm** [comment]
I take a closer look at this deserialization issue this afternoon. I can provide a hot fix, but more work needs to be done. I need to implement proper unit test and add more documentation, maybe this week end.

Can you replace the zotero dependencies entry with the following in `Cargo.toml` :

```
zotero = { git = "https://github.com/Eonm/zotero", branch ="deserialization-fix"}
```
I won't touch anything on [this branch](https://github.com/Eonm/zotero/tree/deserialization-fix) for not braking your code.

Regards,

**Comment by Eonm** [comment]
I didn't notice but the first code you used was in the documentation. It's my fault. The documentation is wrong.
